language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
after_success:
  - docker login -u AWS -p $AWS_DOCKER_LOGIN -e none $HELLOPAGE_REPO_URL
  - cd hellopage
  - sh src/scripts/buildDockerSetup.sh
  - cd src/docker
  - docker build -t hellopage .
  - docker tag hellopage:latest $HELLOPAGE_REPO_URI:$TRAVIS_BRANCH
  - docker push $HELLOPAGE_REPO_URI:$TRAVIS_BRANCH