language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
after_success:
  - docker login -u AWS -p $AWS_DOCKER_LOGIN -e none $HELLOPAGE_REPO_URL
  - docker build -t hellopage .
  - docker tag hellopage:latest $HELLOPAGE_REPO_URI/hellopage:latest
  - docker push $HELLOPAGE_REPO_URI/hellopage:latest