language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker
after_success:
  - pip install --user awscli # install aws cli w/o sudo
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - eval $(aws ecr get-login --region us-west-2) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - cd hellopage
  - sh src/scripts/buildDockerSetup.sh
  - cd src/docker
  - docker build -t hellopage .
  - docker tag hellopage:latest $HELLOPAGE_REPO_URI:$TRAVIS_BUILD_NUMBER
  - docker push $HELLOPAGE_REPO_URI:$TRAVIS_BUILD_NUMBER
  - docker pull 766951526867.dkr.ecr.us-west-2.amazonaws.com/deployer:master
  - docker images
  - docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_REGION=$AWS_REGION -e MESSAGE_TO_SEND=$MESSAGE_TO_SEND 766951526867.dkr.ecr.us-west-2.amazonaws.com/deployer:master
