language: java
jdk:
  - oraclejdk8
script:
  - echo "hello does this work?"
  - docker build -t hellopage .
  - docker login -u AWS -p $AWS_DOCKER_LOGIN -e none $HELLOPAGE_REPO_URL
  - docker tag hellopage:latest $HELLOPAGE_REPO_URI/hellopage:latest
  - docker push $HELLOPAGE_REPO_URI/hellopage:latest